### PR TITLE
Cleaned up submission and implemented suggestions for Property Names

### PR DESCRIPTION
**Pull request by VertexGeneral**
My previous commit included debug files that were unnecessary. I have also implemented the suggestion provided by Bobby to rename the properties to be more clear (Connection String instead of Connection, SQL Statement instead of SQL, and Return Value instead of Return).

### CODE REVIEW

**Comment by bbanet** [comment]
Unless I am mistaken, Action does not pass through the property names.  Only the ID's come through to the assembly when it's called.  I don't believe as posted this will work as intended.

**Comment by VertexGeneral** [comment]
Brian,

I had tested it with properties called Connection, SQL, and Return and that
worked, before I implemented the changed names that Bobby suggested. It
should work with the new property names (Connection String, SQL Statement,
and Return Value). I can check it on my local install tomorrow and let you
know.
On Apr 18, 2016 5:08 PM, "bbanet" notifications@github.com wrote:

Unless I am mistaken, Action does not pass through the property names. Only
the ID's come through to the assembly when it's called. I don't believe as
posted this will work as intended.

**Comment by VertexGeneral** [comment]
Hello,

I created a table in my database with an email address and an ID to test
this. I set up my GlobalAction as shown in this image:
http://puu.sh/oo1BC/a80aa427a6.png

When I ran my documents through the workflow, the assembly was able to pick
up the email address from my database table and apply it to my documents in
the BrewHaven database (http://puu.sh/oo1Ie/d61f9ddcb0.png).

_Shaun Webb_
_Professional Services Analyst_
Square 9® Softworks
Office: 203.789.0889 | Direct: 203.745.2956 | www.square-9.com

_[image: LOGO_03 Solid]_ http://www.square-9.com/

[image:
https://ci5.googleusercontent.com/proxy/EakE5rBmIXYVaV_-0Q1Ez_A7_Q0xwyusQ_RuSHKLBlP3RrI7SaMqNMaLUfSPXMJiMhri-kXnze6nKsBXtSzM7UwZRGqvvnmKKCyNwJ4_uzdr0t_deA=s0-d-e1-ft#http://www.square-9.com/wp-content/uploads/2012/06/facebook.png]
https://www.facebook.com/Square9Softworks     [image:
https://ci5.googleusercontent.com/proxy/bvRt3dEB5PXQpo_i__NxU70Q6vDvwvMV69YZayfYTyogwx472t-SL2XpQyJDXm4HBdmrLMS1QTmxqMES5_L1ioSzMoi6KdnbelDBfdW816zjBNhc=s0-d-e1-ft#http://www.square-9.com/wp-content/uploads/2012/06/twitter.png]
https://twitter.com/S9Softworks     [image:
https://ci3.googleusercontent.com/proxy/N2zlIgP2-N3zQ2hg1g5RriZL_nkpq-1MzJ5PTimftPN39r4PRp0JqawOFezSMMEkz5HCDK7tqheg9sviehJDAFFmQinRtIgHwf3-ogjf9vMoWL0lIQ=s0-d-e1-ft#http://www.square-9.com/wp-content/uploads/2012/06/linkedin.png]
http://www.linkedin.com/company/300875?trk=tyah     [image:
https://ci5.googleusercontent.com/proxy/uAEsguXXUtxJo6KhOaCzHRctvRvucwxQPjbaUW7Wn3BqzdlzOwmOkKopepzK_FsTaUkxNvTGs7EmSXylDrb62aKadWsbhxIsoS39vPzcVqBczaZX=s0-d-e1-ft#http://www.square-9.com/wp-content/uploads/2012/06/youtube.png]
http://www.youtube.com/Square9Softworks

http://www.encompassconference.com/

Disclaimer: This message (including any attachments) contains confidential
information intended for a specific individual and purpose, and is
protected by law. If you are not the intended recipient, you should delete
this message. Any disclosure, copying, or distribution of this message, or
the taking of any action based on it, is strictly prohibited.

_From:_ bbanet [mailto:notifications@github.com]
_Sent:_ Monday, April 18, 2016 5:09 PM
_To:_ Square9Softworks/CallAssemblyExamples <
CallAssemblyExamples@noreply.github.com>
_Cc:_ VertexGeneral swebb@square-9.com
_Subject:_ Re: [Square9Softworks/CallAssemblyExamples] Cleaned up
submission and implemented suggestions for Property Names (#2)

Unless I am mistaken, Action does not pass through the property names. Only
the ID's come through to the assembly when it's called. I don't believe as
posted this will work as intended.

**Comment by bbanet** [comment]
The approach is invalid and will not work.  The RunCallAssembly method receives a Dictionary <string, string> from Action.  That dictionary, in the case of user defined properties in Action contains the Property ID and its corresponding value.  That's it.  If you want to dynamically set the property ID in code, you would need to create some kind of mapping config file.

**Pull request closed without merging**
